#
#
#
version: "3.2"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./:/app
      - ./docker/php/site.ini:/usr/local/etc/php/conf.d/site.ini